# Generated by Django 6.1.1 on 2026-09-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['province', 'city']},
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='province',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
