# Generated by Django 5.2.17 on 2026-10-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_shippingrate_options_shippingrate_province'),
        ('products', '0002_product_is_best_seller'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'weight_grams'), name='unique_cart_product_weight'),
        ),
    ]
