# Generated by Django 6.1.1 on 2026-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='گالری شمین', max_length=100, verbose_name='نام فروشگاه')),
                ('support_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='تلفن پشتیبانی')),
                ('support_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل پشتیبانی')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='آدرس')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='اینستاگرام')),
                ('telegram_url', models.URLField(blank=True, default='', verbose_name='تلگرام')),
                ('announcement', models.CharField(blank=True, default='', max_length=200, verbose_name='اعلان سایت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'تنظیمات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه',
            },
        ),
    ]
