# Generated by Django 6.1.1 on 2026-09-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_storesetting'),
        ('accounts', '0003_adminnotification'),
    ]

    operations = [
    ]
