# Generated by Django 5.2.17 on 2026-10-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='موبایل')),
                ('password', models.CharField(max_length=128, verbose_name='هش رمز عبور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام در انتظار تأیید',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای در انتظار تأیید',
            },
        ),
    ]
