# Generated by Django 5.2.17 on 2026-10-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم (گرم)'),
        ),
    ]
